import "./globals.css";
import 'aos/dist/aos.css'; // Import the CSS
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'react-toastify/dist/ReactToastify.css';
import RootLayout from "./MainApp";





export const metadata = {
  title: "Home | Webbriks",
  description: "Generated by create next app",
};


export default function MyFunc({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="icon" type="image/png" href="https://iili.io/dj5tSSf.png" />
      </head>

      <body className="bg-[#FFFBF4]">
        <RootLayout>
          {children}
        </RootLayout>
      </body>
    </html>

  );
}
